In [1]:
pip install Numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
pip install SymPy

In [4]:
pip install SciPy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\taeeu\anaconda3\python.exe -m pip install --upgrade pip' command.


In [5]:
pip install Pandas

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\taeeu\anaconda3\python.exe -m pip install --upgrade pip' command.


In [6]:
pip install sklearn

  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1321 sha256=6193e846ba0b087ae71c737c78b8cb0c840df656f5375943b89cdeb1143ed782
  Stored in directory: c:\users\taeeu\appdata\local\pip\cache\wheels\22\0b\40\fd3f795caaa1fb4c6cb738bc1f56100be1e57da95849bfc897
Successfully built sklearn
Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\taeeu\anaconda3\python.exe -m pip install --upgrade pip' command.


In [8]:
pip install statsmodels

Note: you may need to restart the kernel to use updated packages.


In [10]:
pip install matplotlib

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\taeeu\anaconda3\python.exe -m pip install --upgrade pip' command.


In [11]:
pip install patsy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\taeeu\anaconda3\python.exe -m pip install --upgrade pip' command.


In [12]:
pip install seaborn

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\taeeu\anaconda3\python.exe -m pip install --upgrade pip' command.


In [9]:
pip install bs4

Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install plotly

Note: you may need to restart the kernel to use updated packages.


In [4]:
pip install newspaper3k

  Created wheel for tinysegmenter: filename=tinysegmenter-0.3-py3-none-any.whl size=13543 sha256=14f758b022c37aae0cb39dbcf90552e82bd38356fbc4e03712f879bdb4b09a60
  Stored in directory: c:\users\taeeu\appdata\local\pip\cache\wheels\99\74\83\8fac1c8d9c648cfabebbbffe97a889f6624817f3aa0bbe6c09
  Created wheel for feedfinder2: filename=feedfinder2-0.0.4-py3-none-any.whl size=3362 sha256=fa92ca9bee54c81e125879102fa23277b5f173678071d88af8826223cf0852e2
  Stored in directory: c:\users\taeeu\appdata\local\pip\cache\wheels\b6\09\68\a9f15498ac02c23dde29f18745bc6a6f574ba4ab41861a3575
  Created wheel for jieba3k: filename=jieba3k-0.35.1-py3-none-any.whl size=7398411 sha256=5ddb966c5da88f964faa5ce103703d072d284fb71d9ed801e9f9a6f236ef415e
  Stored in directory: c:\users\taeeu\appdata\local\pip\cache\wheels\1f\7e\0c\54f3b0f5164278677899f2db08f2b07943ce2d024a3c862afb
  Created wheel for sgmllib3k: filename=sgmllib3k-1.0.0-py3-none-any.whl size=6070 sha256=4f08d7b85a7719a1b82c4c39e43b04e57b6a29f1f0deec7

In [5]:
pip install scikit-image

Note: you may need to restart the kernel to use updated packages.


In [12]:
import numpy as np
data=np.array([[1,2], [3,4], [5,6]])
print(data.shape)
print(data.size)
print(data.ndim)
print(data.dtype)

(3, 2)
6
2
int32


In [16]:
#데이터 타입 바꾸기
print(np.array([1,2,3], dtype=np.int))
print(np.array([1,2,3], dtype=np.float))
print(np.array([1,2,3], dtype=np.complex))

[1 2 3]
[1. 2. 3.]
[1.+0.j 2.+0.j 3.+0.j]


In [17]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones(4)

array([1., 1., 1., 1.])

In [21]:
np.full(3,3.2)

array([3.2, 3.2, 3.2])

In [24]:
data=np.ones(4)
data.fill(3)

In [26]:
np.arange(0,12,4)

array([0, 4, 8])

In [27]:
np.random.rand(2)

array([0.5951251 , 0.65517401])

In [28]:
np.diag(np.arange(0,30,10))

array([[ 0,  0,  0],
       [ 0, 10,  0],
       [ 0,  0, 20]])

In [38]:
a=np.arange(0,11)
print(a[0])
print(a[-1])
print(a[4])
print(a[0:5])
print(a[0:5:2])
print(a[:5])
print(a[-5:])
print(a[0:0:-2])

0
10
4
[0 1 2 3 4]
[0 2 4]
[0 1 2 3 4]
[ 6  7  8  9 10]
[]


In [40]:
a=np.array([[1,2,3,4],[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(a[:,1]) #2번째 열의 모든 수를 뽑아라
print(a[1,:]) #2번째 행의 모든 수를 뽑아라
print(a[:2,:2]) #처음 두개행, 처음 두개열에 해당하는 수
print(a[2:,:2]) #두번째 열부터 끝까지, 1,3,21,23
print(a[::2,::2]) #2개마다 건너뜀 
print(a[1::2,1::2]) # 2개마다 건너뜀 12,14,32,34

[ 2 12 22 32]
[11 12 13 14]
[[ 1  2]
 [11 12]]
[[21 22]
 [31 32]]
[[ 1  3]
 [21 23]]
[[12 14]
 [32 34]]


In [44]:
A=np.linspace(0,1,11)
A
print(A[np.array([0,2,4])])
print(A[A>0.5])
print(A[np.arange(2,5)])

[0.  0.2 0.4]
[0.6 0.7 0.8 0.9 1. ]
[0.2 0.3 0.4]


In [55]:
#1
data=np.array([[1,2], [3,4]])
data
np.reshape(data, (1,4))
data.flatten() #1차원으로 바꿔줌
#2
data=np.arange(5)
print(np.vstack((data,data,data))) #세로로 쌓음
print(np.hstack((data,data))) #가로로 쌓음

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[0 1 2 3 4 0 1 2 3 4]


In [60]:
a=np.arange(3)
b=np.arange(4)
a
b
np.concatenate((a,b))
np.append(a,[3,4,5])
np.resize(b, (2,3)) #b의 4개를 2*3으로 바꿈, 모자란 만큼 b로 채움

array([[0, 1, 2],
       [3, 0, 1]])

In [69]:
np.cos(np.pi) #180도 기준 cos1에서 시작
np.sin(np.pi)
np.tan(np.pi)
print(np.sqrt(4))
print(np.log2(8))
print(np.log10(100))

2.0
3.0
2.0


2.0

In [77]:
a=[1,2,3]
b=[2,4,6]
print(np.add(a,b))
print(np.subtract(b,a))
print(np.multiply(a,b))
print(np.divide(b,a))
print("------")
print(np.power(2,3)) #2의 3승
print(np.remainder(8,3)) #나눈 나머지
print(np.reciprocal(0.5))
print(np.abs(-5.0))
print(np.sign(-5.0))
print(np.round(3.4124,2))

[3 6 9]
[1 2 3]
[ 2  8 18]
[2. 2. 2.]
------
8
2
2.0
5.0
-1.0
3.41


In [80]:
a=np.arange(0,10)
print(a)
print(np.mean(a))
print(np.std(a))
print(np.var(a))
print(np.sum(a))
print(np.prod(a))
print(np.min(a), np.max(a))
print(np.argmin(a), np.argmax(a))
print(np.all(a))
print(np.any(a))

[0 1 2 3 4 5 6 7 8 9]
4.5
2.8722813232690143
8.25
45
0
0 9
0 9
False
True


In [82]:
a=np.linspace(0,16,5)
print(a)
print(np.where(a<5, a, 10*a)) #a보다 작으면 그대로 두고 아니면 10을 곱해라
print(np.choose(2,a)) #a의 세번째를 골라라
print(np.nonzero(a)) #a중 0이 아닌 숫자들의 위치를 구하라
print(np.select([a<2,a>=2],[a-1, a**2])) #a가 2보다 작을때는 a에서 1을 빼고 a가 2보다 크면 2배를 해죠라
print(np.logical_and(a>1, a<10)) #and=>1보다 크고 10보다 작으면 true
print(np.logical_or(a<1, a>15)) 
print(np.logical_not(a>5)) #5보다 크면 false

[ 0.  4.  8. 12. 16.]
[  0.   4.  80. 120. 160.]
8.0
(array([1, 2, 3, 4], dtype=int64),)
[ -1.  16.  64. 144. 256.]
[False  True  True False False]
[ True False False False  True]
[ True  True False False False]


In [84]:
mat=np.arange(9).reshape(3,3)
print(mat)
print(np.transpose(mat))
print(np.fliplr(mat))
print(np.flipud(mat))
print(np.rot90(mat))

c=[[2,3,1], [9,8,7]]
print(c)
print(np.sort(c))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]
[[2 5 8]
 [1 4 7]
 [0 3 6]]
[[2, 3, 1], [9, 8, 7]]
[[1 2 3]
 [7 8 9]]


In [87]:
A=np.arange(1,7).reshape(2,3)
B=np.arange(1,7).reshape(3,2)

print(np.dot(A,B)) #매트릭스 곱 2*2
print(np.outer(B,A)) #가장 큰 차원의 매트릭스를 만들음

c=[2,3,4]
d=[4,5,6]
print(c)
print(d)
print(np.inner(c,d))
print(np.cross(c,d))


[[22 28]
 [49 64]]
[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]
[2, 3, 4]
[4, 5, 6]
47
[-2  4 -2]


In [7]:
#SYMPY BASICS(46p)
import sympy
x=sympy.Symbol("x")
y=sympy.Symbol("y")

expr = 2*(x**2 - x) - x*(x+1)
expr = 2*sympy.cos(x) * sympy.sin(x)
expr = sympy.exp(x)*sympy.exp(y)
expr = 1/(x**2 - 1) + 1 / (x+1)

In [21]:
a,b,c,d=sympy.symbols("a,b,c,d")
M=sympy.Matrix([[a,b], [c,d]])
M*M
x=sympy.Matrix(sympy.symbols("x_1, x_2"))
q=sympy.Matrix(sympy.symbols("q_1, q_2"))
x=M.inv()*q
sympy.solve(M*x - q,x)
print("-------")
print(sympy.transpose(M))
print(sympy.adjoint(M))
print(sympy.trace(M))
print(sympy.det(M))
print(M.inv())

-------
Matrix([[a, c], [b, d]])
Matrix([[conjugate(a), conjugate(c)], [conjugate(b), conjugate(d)]])
a + d
a*d - b*c
Matrix([[d/(a*d - b*c), -b/(a*d - b*c)], [-c/(a*d - b*c), a/(a*d - b*c)]])


In [32]:
N=sympy.Matrix([[-4,2], [6,7]])
print(N)
P=sympy.Matrix([[3,2], [3,2]])
print(P)
print("1.", N.LUdecomposition())
print("2.", N.QRdecomposition())
print("3.", N.diagonalize())
print("4.", N.rank())

sympy.Matrix(P.nullspace())
P.singular_values()

Matrix([[-4, 2], [6, 7]])
Matrix([[3, 2], [3, 2]])
1. (Matrix([
[   1, 0],
[-3/2, 1]]), Matrix([
[-4,  2],
[ 0, 10]]), [])
2. (Matrix([
[-2*sqrt(13)/13, 3*sqrt(13)/13],
[ 3*sqrt(13)/13, 2*sqrt(13)/13]]), Matrix([
[2*sqrt(13), 17*sqrt(13)/13],
[         0, 20*sqrt(13)/13]]))
3. (Matrix([
[-2, 1],
[ 1, 6]]), Matrix([
[-5, 0],
[ 0, 8]]))
4. 2


[sqrt(26), 0]

In [7]:
#웹데이터 가져오기
import pandas as pd
import numpy as np
table_PA = pd.read_html('http://en.wikipedia.org/wiki/Politics_of_Pennsylvania')
len(table_PA) #페이지에 5개의 테이블이 있음(table_PA)->우리는 이 중에 대선결과를 가져오고 싶음
table_PA = pd.read_html('http://en.wikipedia.org/wiki/Politics_of_Pennsylvania', match='Presidential election results') #대선결과와 일치하는 테이블만 긁어옴
len(table_PA)
df=table_PA[0]
df.head()

df['Democratic']=df['Democratic'].str[:4] #Democratic의 앞에 4글자만 추출해라, %길이가 다 똑같기 때문에 가능한일임
df['Republican']=df['Republican'].str[:4]
df.head()
df.info() #확인해보면 숫자가 아니라 문자로 되어있기 때문에 바꿔줌

df[['Democratic', 'Republican']]=df[['Democratic','Republican']].apply(pd.to_numeric) 
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Year        18 non-null     int64 
 1   Democratic  18 non-null     object
 2   Republican  18 non-null     object
dtypes: int64(1), object(2)
memory usage: 560.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Year        18 non-null     int64  
 1   Democratic  18 non-null     float64
 2   Republican  18 non-null     float64
dtypes: float64(2), int64(1)
memory usage: 560.0 bytes


In [49]:
#2
import newspaper #사용하기 간단함, 웹사이트 별로 상이한 결과가 나타남=>뷰티풀수프..?활용하기..복잡하긴 하지만 좋은 결과
from newspaper import Article

article=Article("https://www.3gpp.org/news-events/2143-3gpp-meets-imt-2020")
article.download()
article.parse()

print(article.text)
print(article.title)
print(article.authors)
print(article.publish_date)

November 28, 2020

Earlier this week the ITU issued a press release to publicise the move to the approval process - by the 193 member states of the Union - of their ITU-R Recommendation: 'Detailed specifications of the radio interfaces of IMT-2020.' (ITU-R M.[IMT-2020.SPECS]).

The document - due for publication in February 2021 - will be the end product of a long process, initiated in 2012, under the banner 'IMT for 2020 and beyond' where the ITU set out its agenda for a steady progression of 5G research activities that would nourish the 3GPP efforts on the new radio and 5G core specification work.

The ITU press release formally announces the radio interfaces that conform with the International Mobile Telecommunications 2020 (IMT-2020) performance requirements:

"The technologies are: 3GPP 5G-SRIT and 3GPP 5G-RIT submitted by the Third Generation Partnership Project (3GPP), and 5Gi submitted by Telecommunications Standards Development Society India (TSDSI). During the multi-year deve

In [76]:
#뉴스웹사이트에 들어가서 메인페이지에 있는 여러개 뉴스의 제목,웹주소, 저자, 날짜, 텍스트데이터 불러오기
import newspaper
site = newspaper.build("https://techcrunch.com/", memoize_articles=False) 
site.article_urls()

['https://techcrunch.com/2021/07/07/acrylic-debut-crypto-fund/',
 'https://techcrunch.com/2021/07/07/lacuna-raises-16-million-in-series-a-to-help-cities-manage-mobility-via-digital-twin/',
 'https://techcrunch.com/2021/07/07/outbrain-raises-200-million-ahead-of-its-ipo/',
 'https://techcrunch.com/2021/07/07/a-year-after-expanding-to-europe-nigerian-fintech-lidya-raises-8-3m-to-scale-lending-operations/',
 'https://techcrunch.com/2021/07/07/satellite-operator-planet-to-go-public-in-2-8b-spac-merger/',
 'https://techcrunch.com/2021/07/07/anyvision-the-controversial-facial-recognition-startup-has-raised-235m-led-by-softbank-and-eldridge/',
 'https://techcrunch.com/2021/07/07/localyze-raises-12m-for-a-saas-that-supports-cross-border-hiring-and-relocation/',
 'https://techcrunch.com/2021/07/07/youtubes-recommender-ai-still-a-horrorshow-finds-major-crowdsourced-study/',
 'https://techcrunch.com/2021/07/07/real-estate-platform-casafari-raises-15m-to-allow-pe-to-buy-single-family-homes-at-scal

In [80]:
#첫번째 웹페이지 주소를 대상으로 다운로드하고, 해석하고, 제목이랑 url을 추출함 ...여기서부터 오류남....

allarticles=[]
for i in range(len(site.article_urls())):
    article = Article(site.article_urls() [i])
    article.download()
    article.parse()
    allarticles.append(article)
    
import pandas as pd
df=pd.DataFrame(columns=['Title', 'Authors', 'PubDate', 'URL', 'Text'])
                         
for i in range(len(allarticles)):
                         row=dict(zip(['Title','Authors','PubDate','URL','Text'],[allarticles[i].title, allarticles[i].authors, allarticles[i].publish_date, allarticles[i].url, allarticles[i].text]))
                         row_s = pd.Series(row)
                         row_s.name=i
                         df = df.append(row_s)
df

Title Authors    PubDate  \
0   Acrylic raises debut $55M solo GP fund to pain...      [] 2021-07-07   
1   Lacuna raises $16 million in Series A to help ...      [] 2021-07-07   
2   Outbrain raises $200 million ahead of its IPO ...      [] 2021-07-07   
3   A year after expanding to Europe, Nigerian fin...      [] 2021-07-07   
4   Satellite operator Planet to go public in $2.8...      [] 2021-07-07   
5   AnyVision, the controversial facial recognitio...      [] 2021-07-07   
6   Localyze raises $12M for a SaaS that supports ...      [] 2021-07-07   
7   YouTube’s recommender AI still a horrorshow, f...      [] 2021-07-07   
8   Real estate platform Casafari raises $15M to a...      [] 2021-07-07   
9                Dispatch from Bangalore – TechCrunch      [] 2021-07-06   
10  Renegade Partners rolls out its much-anticipat...      [] 2021-07-06   
11  Juni, a ‘vertical’ neobank for e-commerce and ...      [] 2021-07-06   
12  Extra Crunch roundup: Video pitch decks, Didi’...      [] 2021-07-06   
13  Daily Crunch: Nothing sets July 27 rollout for...      [] 2021-07-06   
14  Gettr, the latest pro-Trump social network, is...      [] 2021-07-06   
15  Sarah Guo, Kobie Fuller & Casey Aylward headli...      [] 2021-07-06   
16  To stay ahead of your competitors, start build...      [] 2021-07-06   
17  Yandex Self-Driving Group partners with GrubHu...      [] 2021-07-06   
18  Nextdoor’s SPAC investor deck paints a picture...      [] 2021-07-06   
19  Announcing the startups pitching at TC Early S...      [] 2021-07-06   

                                                  URL  \
0   https://techcrunch.com/2021/07/07/acrylic-debu...   
1   https://techcrunch.com/2021/07/07/lacuna-raise...   
2   https://techcrunch.com/2021/07/07/outbrain-rai...   
3   https://techcrunch.com/2021/07/07/a-year-after...   
4   https://techcrunch.com/2021/07/07/satellite-op...   
5   https://techcrunch.com/2021/07/07/anyvision-th...   
6   https://techcrunch.com/2021/07/07/localyze-rai...   
7   https://techcrunch.com/2021/07/07/youtubes-rec...   
8   https://techcrunch.com/2021/07/07/real-estate-...   
9   https://techcrunch.com/2021/07/06/indian-start...   
10  https://techcrunch.com/2021/07/06/renegade-par...   
11  https://techcrunch.com/2021/07/06/juni-a-verti...   
12  https://techcrunch.com/2021/07/06/extra-crunch...   
13  https://techcrunch.com/2021/07/06/daily-crunch...   
14  https://techcrunch.com/2021/07/06/gettr-trump-...   
15  https://techcrunch.com/2021/07/06/sarah-guo-ko...   
16  https://techcrunch.com/2021/07/06/to-stay-ahea...   
17  https://techcrunch.com/2021/07/06/yandex-self-...   
18  https://techcrunch.com/2021/07/06/nextdoors-sp...   
19  https://techcrunch.com/2021/07/06/announcing-t...   

                                                 Text  
0   It’s been quite the year for crypto capital, w...  
1   Lacuna Technologies, a startup that helps citi...  
2   Outbrain, an adtech company that provides clic...  
3   Nigerian fintech and lending startup Lidya tod...  
4   Planet, which operates a network of around 200...  
5   Facial recognition has been one of the more co...  
6   Y-Combinator-backed Localyze has nabbed $12 mi...  
7   For years YouTube’s video-recommending algorit...  
8   Just a Spotify used VC and PE backing to acqui...  
9   Dispatch from Bangalore Indian startups have r...  
10  Renegade Partners — a Bay Area-based venture f...  
11  E-commerce in Europe is expected to grow 30% t...  
12  The numbers don’t lie.\n\nAccording to DocSend...  
13  To get a roundup of TechCrunch’s biggest and m...  
14  Well, that was fast. Just days after a Twitter...  
15  While SaaS has become the default way to deliv...  
16  Having a unique product used to give you at le...  
17  Yandex Self-Driving Group, a unit of Yandex, t...  
18  The SPAC parade continues in this shortened we...  
19  This Thursday and Friday, TechCrunch will host...

In [36]:
#Forbes.com스크랩들의 공통점을 F12를 눌러서 파악한다
import urllib.request as ure
from bs4 import BeautifulSoup as bs

news='http://www.forbes.com/'
soup=bs(ure.urlopen(news).read(), 'html.parser')

soup.find_all('a', {"class": "happening__title"})

for i in soup.find_all('a', {"class":"happening__title"}):
    print(i.text)
for i in soup.find_all('a', {"class":"happening__title"}):
    print(i.get('href'))

U.S. Says Thousands Of Yemenis Can’t Be Deported From U.S.—5th Group Protected This Year
Adams Wins NYC Mayoral Primary By Just 1 Point, AP Says
Black Louisiana Lawmakers Request Federal Probe Into State Police After Black Man Dies In Custody
RNC Denies Russian Government Hacked Its Computers
McConnell Vows To ‘Make It Hard’ For Democrats To Pass Reconciliation Bill
Miami Condo Collapse: Death Toll Rises To 36 As Search Resumes After Building Demolition
Cuomo Declares Disaster Emergency On Gun Violence, Labeling It A ‘New Epidemic’
Maryland Says 100% Of June Covid Deaths Were Among The Unvaccinated, As Early Data Shows Similar Trend Nationally
Medicare Would Save $2.6 Billion Buying Some Generic Drugs At Costco Prices, Researchers Find
Hundreds Likely Dead After Historic Heat Wave Hits Pacific Northwest And Canada
White House Says U.S. Not ‘On Track’ For New Covid Restrictions As Delta Variant Spreads
Ex-Surgeon General: People ‘Are Dying’ Because FDA Hasn’t Fully Approved A Covid-19 V

In [40]:
#텍스트데이터는 한번 더 적용
article1 = 'https://www.forbes.com/sites/siladityaray/2021/07/06/us-lawyer-handed-prison-sentence-in-hong-kong-over-scuffle-with-police-during-2019-protests/?sh=ff8d6ab3adea'

soup2 = bs(ure.urlopen(article1).read(),'html.parser')

for i in soup2.find_all('p'):
            print(i.text)

A Hong Kong court on Tuesday sentenced an American lawyer to four and a half months in prison for clashing with a plainclothes police officer during the 2019 pro-democracy protests in the city, a move that comes at a time when several foreign workers are considering leaving the financial hub following Beijing’s crackdown on all forms of dissent in the city.
Riot police secure the area outside the Tung Chung MTR station on September 7, 2019 in Hong Kong, ... [+] China. 
Samuel Bickett, a 37-year old former Bank of America Merrill Lynch employee, was charged with assaulting a police officer and was handed a jail term of four months and two weeks, Bloomberg reported.
The judge who handed out the ruling described Bickett’s actions as a “serious threat to public order.”
Bickett had been found guilty on the assault charge last month and was denied bail.
The lawyer had pleaded not guilty last month and had accused the off-duty officer of needlessly brandishing his baton at him.
The police off

In [41]:
happening=soup.find_all('a', {"class":"happening__title"})

rows=[]
for i in range(len(happening)):
    happeningtitle=happening[i].text
    happeningurl=happening[i].get('href')
    soup2=bs(ure.urlopen(happeningurl).read(), 'html.parser')
    txt=""
    for j in soup2.find_all('p'):
        txt=txt+j.text
    rows.append({'Title': happeningtitle, 'URL':happeningurl, 'Text':txt})

In [43]:
import pandas as pd
df=pd.DataFrame(rows, columns=['Title', 'URL', 'Text'])
df

Title  \
0   U.S. Says Thousands Of Yemenis Can’t Be Deport...   
1   Adams Wins NYC Mayoral Primary By Just 1 Point...   
2   Black Louisiana Lawmakers Request Federal Prob...   
3   RNC Denies Russian Government Hacked Its Compu...   
4   McConnell Vows To ‘Make It Hard’ For Democrats...   
5   Miami Condo Collapse: Death Toll Rises To 36 A...   
6   Cuomo Declares Disaster Emergency On Gun Viole...   
7   Maryland Says 100% Of June Covid Deaths Were A...   
8   Medicare Would Save $2.6 Billion Buying Some G...   
9   Hundreds Likely Dead After Historic Heat Wave ...   
10  White House Says U.S. Not ‘On Track’ For New C...   
11  Ex-Surgeon General: People ‘Are Dying’ Because...   
12  Bahamas Flight Postponed After High School Stu...   
13  ESPN’s Rachel Nichols Pulled As NBA Finals Sid...   
14  Pentagon Scraps Microsoft’s $10 Billion Cloud ...   
15  Pfizer Shot Much Less Effective Against Delta,...   
16  ‘Unheard Of’: Oklahoma GOP Chair Backs Challen...   
17  New Record Set For Most Expensive Sports Card:...   
18  Capitol Rioter Killed In Motorcycle Crash Whil...   
19  Capitol Police Opening Field Offices In Califo...   
20  DOJ Still Searching For At Least 300 Capitol R...   

                                                  URL  \
0   https://www.forbes.com/sites/graisondangor/202...   
1   https://www.forbes.com/sites/joewalsh/2021/07/...   
2   https://www.forbes.com/sites/nicholasreimann/2...   
3   https://www.forbes.com/sites/joewalsh/2021/07/...   
4   https://www.forbes.com/sites/andrewsolender/20...   
5   https://www.forbes.com/sites/nicholasreimann/2...   
6   https://www.forbes.com/sites/jackbrewster/2021...   
7   https://www.forbes.com/sites/jemimamcevoy/2021...   
8   https://www.forbes.com/sites/graisondangor/202...   
9   https://www.forbes.com/sites/nicholasreimann/2...   
10  https://www.forbes.com/sites/andrewsolender/20...   
11  https://www.forbes.com/sites/jackbrewster/2021...   
12  https://www.forbes.com/sites/alisondurkee/2021...   
13  https://www.forbes.com/sites/nicholasreimann/2...   
14  https://www.forbes.com/sites/joewalsh/2021/07/...   
15  https://www.forbes.com/sites/roberthart/2021/0...   
16  https://www.forbes.com/sites/andrewsolender/20...   
17  https://www.forbes.com/sites/tommybeer/2021/07...   
18  https://www.forbes.com/sites/jemimamcevoy/2021...   
19  https://www.forbes.com/sites/andrewsolender/20...   
20  https://www.forbes.com/sites/jemimamcevoy/2021...   

                                                 Text  
0   Nearly 2,200 people from Yemen in the U.S. can...  
1   Eric Adams has defeated Kathryn Garcia by just...  
2   Lawmakers with the Louisiana Legislative Black...  
3   A third-party IT company tied to the Republica...  
4   Senate Minority Leader Mitch McConnell said Tu...  
5   At least 36 people are now confirmed dead whil...  
6   Just two weeks after his emergency powers agai...  
7   Every person who died from Covid-19 in Marylan...  
8   Medicare pays billions of dollars more for com...  
9   The death toll in Oregon alone is now more tha...  
10  White House press secretary Jen Psaki said Tue...  
11  Former U.S. Surgeon General Jerome Adams on Tu...  
12  An American Airlines flight from Charlotte, No...  
13  Longtime ESPN reporter Rachel Nichols will not...  
14  The Department of Defense is canceling a $10 b...  
15  Pfizer’s Covid-19 vaccine is significantly les...  
16  The chair of the Oklahoma Republican Party has...  
17  Alt Fund II, an investment fund managed by alt...  
18  A 34-year-old Texas man charged with multiple ...  
19  The Capitol Police on Tuesday announced the cr...  
20  Though more than 500 people have already been ...